console.time();
console.group('boolean');
console.log(true);
console.log(false);
console.groupEnd('boolean');
console.group('null');
console.log(null);
console.groupEnd('null');
console.group('string');
console.log('hello');
console.log("Hello");
console.log(`hello`);
console.groupEnd('string');
console.group('numeric');
console.log(1);
console.log(0b011);
console.log(0o754);
console.log(0xfff);
console.groupEnd('numeric');
console.group('RegExp');
console.log(/./g);
console.groupEnd('RegExp');
console.group('undefined');
console.log('undefined');
console.groupEnd('undefined');
console.timeEnd();
// var a = prompt('how is your age', 0);
// console.log('Your age is ' + a);
var text = '\u0048\u0065\u006C\u006C\u006F\u0020\u0077\u006F\u0072\u006C\u0064';
console.log(text);
console.error('My error1');